name: Build Aseprite
on: [push, workflow_dispatch]  # 支持手动触发

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 必须递归检出子模块 [1,3](@ref)

      - name: Install Dependencies
        run: |
          # 根据系统安装 CMake/Ninja (参考上文)
          # 编译 Skia (需缓存加速)
          # Windows 安装 MSVC [1](@ref)

      - name: Configure and Build
        env:
          SKIA_DIR: ${{ github.workspace }}/skia
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$SKIA_DIR \
            -DSKIA_LIBRARY_DIR=$SKIA_DIR/out/Release-${{ runner.arch }} \
            -G Ninja
          ninja aseprite

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aseprite-${{ runner.os }}-${{ runner.arch }}
          path: build/bin/aseprite
