name: Build Aseprite
on:
  workflow_dispatch:
    inputs:
      aseprite_version:  # 动态输入 Aseprite 版本
        description: "Aseprite Version (e.g v1.3.13)"
        required: true
        default: "v1.3.13"
      skia_arch:  # 动态选择 Skia 架构
        description: "Skia Architecture (x64/arm64)"
        required: true
        default: "x64"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # 1. 动态下载 Aseprite 源码（核心修复！）
      - name: Download Aseprite Source
        run: |
          VERSION=${{ github.event.inputs.aseprite_version }}
          # 官方 Release 源码包地址（固定格式）
          URL="https://github.com/aseprite/aseprite/archive/refs/tags/${VERSION}.zip"
          wget "$URL" -O aseprite-src.zip
          unzip aseprite-src.zip
          mv aseprite-${VERSION#v} aseprite-src

      # 2. 安装 Skia（根据参数选择架构）
      - name: Install Skia
        run: |
          ARCH=${{ github.event.inputs.skia_arch }}
          # 官方预编译 Skia 地址（动态匹配架构）
          SKIA_URL="https://github.com/aseprite/skia/releases/download/m102/Skia-${{ runner.os }}-Release-${{ github.event.inputs.skia_arch }}.zip"
          wget "$SKIA_URL" -O skia.zip
          unzip skia.zip -d skia-${{ github.event.inputs.skia_arch }}

      # 3. 编译配置（传递动态路径）
      - name: Configure and Build
        env:
          SKIA_DIR: ${{ github.workspace }}/skia-${{ github.event.inputs.skia_arch }}
        run: |
          cd aseprite-src
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR="$SKIA_DIR" \
            -DSKIA_LIBRARY_DIR="$SKIA_DIR/out/Release-${{ github.event.inputs.skia_arch }}" \
            ${{ matrix.os == 'macos-latest' && '-DCMAKE_OSX_ARCHITECTURES=arm64' || '' }} \
            -G Ninja
          ninja aseprite

      # 4. 上传产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ runner.os }}-${{ github.event.inputs.skia_arch }}
          path: aseprite-src/build/bin/aseprite*
