name: Build Aseprite M
on:
  workflow_dispatch:
    inputs:
      aseprite_version:
        description: "Aseprite 版本号 (例如 v1.3.14.2)"
        required: true
        default: "v1.3.14.2"
      aseprite_source_url:
        description: "自定义源码包地址 (可选)"
        required: false
        default: ""
      skia_arch:
        description: "Skia 架构 (x64/arm64)"
        required: true
        default: "x64"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # 动态定义 Skia 架构（Mac 强制 arm64）
        include:
          - os: macos-latest
            skia_arch: arm64
          - os: ubuntu-latest
            skia_arch: x64
          - os: windows-latest
            skia_arch: x64

    steps:
      # 1. 下载 Aseprite 源码（硬编码您的默认地址）
      - name: Download Aseprite Source
        run: |
          if [ -z "${{ inputs.aseprite_source_url }}" ]; then
            # 使用您指定的默认地址（v1.3.14.2）
            SOURCE_URL="https://github.com/aseprite/aseprite/releases/download/${{ inputs.aseprite_version }}/Aseprite-${{ inputs.aseprite_version }}-Source.zip"
          else
            SOURCE_URL="${{ inputs.aseprite_source_url }}"
          fi
          wget "$SOURCE_URL" -O aseprite-src.zip
          unzip aseprite-src.zip
          mv Aseprite-${{ inputs.aseprite_version }}-Source aseprite-src

      # 2. 安装 Skia（Mac 地址硬编码，其他平台动态生成）
      - name: Install Skia
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            # macOS 专用地址（官方 M102 稳定版）
            SKIA_URL="https://github.com/aseprite/skia/releases/download/m102/Skia-macOS-Release-arm64.zip"
          else
            # 其他平台动态生成
            SKIA_URL="https://github.com/aseprite/skia/releases/download/m102/Skia-${{ runner.os }}-Release-${{ matrix.skia_arch }}.zip"
          fi
          wget "$SKIA_URL" -O skia.zip
          unzip skia.zip -d skia-${{ matrix.skia_arch }}

      # 3. 编译配置
      - name: Configure and Build
        env:
          SKIA_DIR: ${{ github.workspace }}/skia-${{ matrix.skia_arch }}
        run: |
          cd aseprite-src
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR="$SKIA_DIR" \
            -DSKIA_LIBRARY_DIR="$SKIA_DIR/out/Release-${{ matrix.skia_arch }}" \
            ${{ matrix.os == 'macos-latest' && '-DCMAKE_OSX_ARCHITECTURES=arm64' || '' }} \
            -G Ninja
          ninja aseprite

      # 4. 上传产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ runner.os }}-${{ matrix.skia_arch }}
          path: aseprite-src/build/bin/aseprite*
