name: Build Aseprite Mac
on:
  workflow_dispatch:
    inputs:
      aseprite_version:
        description: "Aseprite Version (e.g v1.3.13)"
        required: true
        default: "v1.3.13"
      skia_link:  # 用户可自定义 Skia 预编译包链接
        description: "Prebuilt Skia Download URL (Optional)"
        required: false  # 非必填
        default: "https://github.com/aseprite/skia/releases/download/m102/Skia-${{ runner.os }}-Release-${{ matrix.skia_arch }}.zip"
      aseprite_source_url:  # 用户可自定义源码包地址
        description: "Aseprite Source Archive URL (Optional)"
        required: false
        default: "https://github.com/aseprite/aseprite/archive/refs/tags/${{ github.event.inputs.aseprite_version }}.zip"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        skia_arch:  # 动态匹配架构
          ubuntu-latest: "x64"
          macos-latest: "arm64"
          windows-latest: "x64"

    steps:
      # 1. 动态下载 Aseprite 源码（用户可覆盖默认地址）
      - name: Download Aseprite Source
        run: |
          SOURCE_URL="${{ github.event.inputs.aseprite_source_url || 'https://github.com/aseprite/aseprite/archive/refs/tags/${{ github.event.inputs.aseprite_version }}.zip' }}"
          wget "$SOURCE_URL" -O aseprite-src.zip
          unzip aseprite-src.zip
          mv aseprite-${ { github.event.inputs.aseprite_version#v } } aseprite-src

      # 2. 安装 Skia（用户可覆盖默认链接）
      - name: Install Skia
        run: |
          SKIA_URL="${{ github.event.inputs.skia_link || 'https://github.com/aseprite/skia/releases/download/m102/Skia-${{ matrix.os }}-Release-${{ matrix.skia_arch }}.zip' }}"
          wget "$SKIA_URL" -O skia.zip
          unzip skia.zip -d skia-${{ matrix.skia_arch }}

      # 3. 编译配置（自动传递路径）
      - name: Configure and Build
        env:
          SKIA_DIR: ${{ github.workspace }}/skia-${{ matrix.skia_arch }}
        run: |
          cd aseprite-src
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR="$SKIA_DIR" \
            -DSKIA_LIBRARY_DIR="$SKIA_DIR/out/Release-${{ matrix.skia_arch }}" \
            ${{ matrix.os == 'macos-latest' && '-DCMAKE_OSX_ARCHITECTURES=arm64' || '' }} \
            -G Ninja
          ninja aseprite

      # 4. 上传产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ runner.os }}-${{ matrix.skia_arch }}
          path: aseprite-src/build/bin/aseprite*
